<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>C__200_Example</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Example_001.cs" />
    <Compile Remove="Example_002.cs" />
    <Compile Remove="Example_003.cs" />
    <Compile Remove="Example_004.cs" />
    <Compile Remove="Example_005.cs" />
    <Compile Remove="Example_006.cs" />
    <Compile Remove="Example_007.cs" />
    <Compile Remove="Example_008.cs" />
    <Compile Remove="Example_009.cs" />
    <Compile Remove="Example_01.cs" />
    <Compile Remove="Example_010.cs" />
    <Compile Remove="Example_011.cs" />
    <Compile Remove="Example_012.cs" />
    <Compile Remove="Example_013.cs" />
    <Compile Remove="Example_014.cs" />
    <Compile Remove="Example_015.cs" />
    <Compile Remove="Example_016.cs" />
    <Compile Remove="Example_017.cs" />
    <Compile Remove="Example_018.cs" />
    <Compile Remove="Example_019.cs" />
    <Compile Remove="Example_02.cs" />
    <Compile Remove="Example_020.cs" />
    <Compile Remove="Example_021.cs" />
    <Compile Remove="Example_022.cs" />
    <Compile Remove="Example_023.cs" />
    <Compile Remove="Example_024.cs" />
    <Compile Remove="Example_025.cs" />
    <Compile Remove="Example_026.cs" />
    <Compile Remove="Example_027.cs" />
    <Compile Remove="Example_028.cs" />
    <Compile Remove="Example_029.cs" />
    <Compile Remove="Example_03.cs" />
    <Compile Remove="Example_030.cs" />
    <Compile Remove="Example_031.cs" />
    <Compile Remove="Example_032.cs" />
    <Compile Remove="Example_033.cs" />
    <Compile Remove="Example_034.cs" />
    <Compile Remove="Example_035.cs" />
    <Compile Remove="Example_036.cs" />
    <Compile Remove="Example_037.cs" />
    <Compile Remove="Example_038.cs" />
    <Compile Remove="Example_039.cs" />
    <Compile Remove="Example_04.cs" />
    <Compile Remove="Example_040.cs" />
    <Compile Remove="Example_041.cs" />
    <Compile Remove="Example_042.cs" />
    <Compile Remove="Example_043.cs" />
    <Compile Remove="Example_044.cs" />
    <Compile Remove="Example_045.cs" />
    <Compile Remove="Example_046.cs" />
    <Compile Remove="Example_047.cs" />
    <Compile Remove="Example_048.cs" />
    <Compile Remove="Example_049.cs" />
    <Compile Remove="Example_05.cs" />
    <Compile Remove="Example_050.cs" />
    <Compile Remove="Example_051.cs" />
    <Compile Remove="Example_052.cs" />
    <Compile Remove="Example_053.cs" />
    <Compile Remove="Example_054.cs" />
    <Compile Remove="Example_055.cs" />
    <Compile Remove="Example_056.cs" />
    <Compile Remove="Example_057.cs" />
    <Compile Remove="Example_058.cs" />
    <Compile Remove="Example_059.cs" />
    <Compile Remove="Example_06.cs" />
    <Compile Remove="Example_060.cs" />
    <Compile Remove="Example_061.cs" />
    <Compile Remove="Example_062.cs" />
    <Compile Remove="Example_063.cs" />
    <Compile Remove="Example_064.cs" />
    <Compile Remove="Example_065.cs" />
    <Compile Remove="Example_066.cs" />
    <Compile Remove="Example_067.cs" />
    <Compile Remove="Example_068.cs" />
    <Compile Remove="Example_069.cs" />
    <Compile Remove="Example_07.cs" />
    <Compile Remove="Example_070.cs" />
    <Compile Remove="Example_071.cs" />
    <Compile Remove="Example_072.cs" />
    <Compile Remove="Example_073.cs" />
    <Compile Remove="Example_074.cs" />
    <Compile Remove="Example_075.cs" />
    <Compile Remove="Example_076.cs" />
    <Compile Remove="Example_077.cs" />
    <Compile Remove="Example_078.cs" />
    <Compile Remove="Example_079.cs" />
    <Compile Remove="Example_08.cs" />
    <Compile Remove="Example_080.cs" />
    <Compile Remove="Example_081.cs" />
    <Compile Remove="Example_082.cs" />
    <Compile Remove="Example_083.cs" />
    <Compile Remove="Example_084.cs" />
    <Compile Remove="Example_085.cs" />
    <Compile Remove="Example_086.cs" />
    <Compile Remove="Example_087.cs" />
    <Compile Remove="Example_088.cs" />
    <Compile Remove="Example_089.cs" />
    <Compile Remove="Example_09.cs" />
    <Compile Remove="Example_090.cs" />
    <Compile Remove="Example_091.cs" />
    <Compile Remove="Example_092.cs" />
    <Compile Remove="Example_093.cs" />
    <Compile Remove="Example_094.cs" />
    <Compile Remove="Example_095.cs" />
    <Compile Remove="Example_096.cs" />
    <Compile Remove="Example_097.cs" />
    <Compile Remove="Example_098.cs" />
    <Compile Remove="Example_099.cs" />
    <Compile Remove="Example_10.cs" />
    <Compile Remove="Example_100.cs" />
    <Compile Remove="Example_101.cs" />
    <Compile Remove="Example_102.cs" />
    <Compile Remove="Example_103.cs" />
    <Compile Remove="Example_104.cs" />
    <Compile Remove="Example_105.cs" />
    <Compile Remove="Example_106.cs" />
    <Compile Remove="Example_107.cs" />
    <Compile Remove="Example_108.cs" />
    <Compile Remove="Example_109.cs" />
    <Compile Remove="Example_11.cs" />
    <Compile Remove="Example_110.cs" />
    <Compile Remove="Example_111.cs" />
    <Compile Remove="Example_112.cs" />
    <Compile Remove="Example_113.cs" />
    <Compile Remove="Example_114.cs" />
    <Compile Remove="Example_115.cs" />
    <Compile Remove="Example_12.cs" />
    <Compile Remove="Example_13.cs" />
    <Compile Remove="Example_14.cs" />
    <Compile Remove="Example_15.cs" />
    <Compile Remove="Example_16.cs" />
    <Compile Remove="Example_17.cs" />
    <Compile Remove="Example_18.cs" />
    <Compile Remove="Example_19.cs" />
    <Compile Remove="Example_20.cs" />
    <Compile Remove="Example_21.cs" />
    <Compile Remove="Example_22.cs" />
    <Compile Remove="Example_23.cs" />
    <Compile Remove="Example_24.cs" />
    <Compile Remove="Example_25.cs" />
    <Compile Remove="Example_26.cs" />
    <Compile Remove="Example_27.cs" />
    <Compile Remove="Example_28.cs" />
    <Compile Remove="Example_29.cs" />
    <Compile Remove="Example_30.cs" />
    <Compile Remove="Example_31.cs" />
    <Compile Remove="Example_32.cs" />
    <Compile Remove="Example_33.cs" />
    <Compile Remove="Example_34.cs" />
    <Compile Remove="Example_35.cs" />
    <Compile Remove="Example_36.cs" />
    <Compile Remove="Example_37.cs" />
    <Compile Remove="Example_38.cs" />
    <Compile Remove="Example_39.cs" />
    <Compile Remove="Example_40.cs" />
    <Compile Remove="Example_41.cs" />
    <Compile Remove="Example_42.cs" />
    <Compile Remove="Example_43.cs" />
    <Compile Remove="Example_44.cs" />
    <Compile Remove="Example_45.cs" />
    <Compile Remove="Example_46.cs" />
    <Compile Remove="Example_47.cs" />
    <Compile Remove="Example_48.cs" />
    <Compile Remove="Example_49.cs" />
    <Compile Remove="Example_50.cs" />
    <Compile Remove="Example_51.cs" />
    <Compile Remove="Example_52.cs" />
    <Compile Remove="Example_53.cs" />
    <Compile Remove="Example_54.cs" />
    <Compile Remove="Example_55.cs" />
    <Compile Remove="Example_56.cs" />
    <Compile Remove="Example_57.cs" />
    <Compile Remove="Example_58.cs" />
    <Compile Remove="Example_59.cs" />
    <Compile Remove="Example_60.cs" />
    <Compile Remove="Example_61.cs" />
    <Compile Remove="Example_62.cs" />
    <Compile Remove="Example_63.cs" />
    <Compile Remove="Example_64.cs" />
    <Compile Remove="Example_65.cs" />
    <Compile Remove="Example_66.cs" />
    <Compile Remove="Example_67.cs" />
    <Compile Remove="Example_68.cs" />
    <Compile Remove="Example_69.cs" />
    <Compile Remove="Example_70.cs" />
    <Compile Remove="Example_71.cs" />
    <Compile Remove="Example_72.cs" />
    <Compile Remove="Example_73.cs" />
    <Compile Remove="Example_74.cs" />
    <Compile Remove="Example_75.cs" />
    <Compile Remove="Example_76.cs" />
    <Compile Remove="Example_77.cs" />
    <Compile Remove="Example_78.cs" />
    <Compile Remove="Example_79.cs" />
    <Compile Remove="Example_80.cs" />
    <Compile Remove="Example_81.cs" />
    <Compile Remove="Example_82.cs" />
    <Compile Remove="Example_83.cs" />
    <Compile Remove="Example_84.cs" />
    <Compile Remove="Example_85.cs" />
    <Compile Remove="Example_86.cs" />
    <Compile Remove="Example_87.cs" />
    <Compile Remove="Example_88.cs" />
    <Compile Remove="Example_89.cs" />
    <Compile Remove="Example_90.cs" />
    <Compile Remove="Example_91.cs" />
    <Compile Remove="Example_92.cs" />
    <Compile Remove="Example_93.cs" />
    <Compile Remove="Example_94.cs" />
    <Compile Remove="Example_95.cs" />
    <Compile Remove="Example_96.cs" />
    <Compile Remove="Example_97.cs" />
    <Compile Remove="Example_98.cs" />
    <Compile Remove="Example_99.cs" />
  </ItemGroup>

</Project>
